<?php
 // module/Album/view/album/album/add.phtml:

 $title = "Ajout d'un nouvel utilisateur";
 $this->headTitle($title);
 ?>
<div class="col-xs-12">
    <div class="col-xs-9">
        <h1><?php echo $this->escapeHtml($title); ?></h1> 
    </div>
    <div class="col-xs-3 text-right">
        <input type="button" class="retour  btn btn-info btn-lg" value="Retour" />
    </div>
</div>
<div class="clearfix"></div>
<br/><br/>

<?php
$form->setAttribute('action', $this->url('member/ajouter', array('action' => 'member/ajouter')));
$form->prepare();

echo $this->form()->openTag($form);
foreach($form->getElements() as $element): ?>
    <?php if($element->getLabel()): ?>
        <div class="col-xs-6 text-center"><?php echo $this->formLabel($element) ?></div>
    <?php endif ?>
        
    <?php echo $this->formElementErrors($element, array('class' => 'inline')); ?>
        <div class="col-xs-<?php echo (($element->getLabel())?6:"12 text-center"); ?>"><?php echo $this->formElement($element) ?></div>
<?php endforeach; 
echo $this->form()->closeTag();?>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('.retour').unbind('click').on('click', function(){
            location.href=url_front_application +"member";
        });
    });
</script>