<div class="col-xs-12" style="margin-top: 15%">
    <div class="col-xs-6 text-right" style="padding-top: 5px"><label> Choisir le client souhait&eacute; :</label></div>
    <div class="col-xs-6 form-group" style="text-align: center">
        <select name="choice_client" class="form-control">
            <?php foreach($client as $k => $c) { ?>
            <option value="<?php echo $k; ?>"><?php echo $c; ?></option>            
            <?php } ?>
        </select>   
    </div>
</div>
<div class="clearfix"></div>
<div class="col-xs-12" style="text-align: center">
    <input type="button" class="btn btn-info btn-sm" name="valider_choice_client" value="Valider" />
</div>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('input[name="valider_choice_client"]').unbind('click').on('click', function(){
            if($('select[name="choice_client"]  option:selected').val() != ""){
                location.href=url_front_application +"stock/detail/"+$('select[name="choice_client"]  option:selected').val();
            }
        });
    });
</script>