<div class="col-xs-12" style="margin-top: 35%">
    <form style="width: 40%; margin: auto" action="<?php echo $this->url('login/check', array('action' => 'check')); ?>" method="POST">
        <div class="col-xs-12">
        <div class="col-xs-12">
            <div class="col-xs-6">Login: </div>
            <div class="col-xs-6"><input type="text" value="" autocomplete="false" placeholder="Login" name="login" /></div>
        </div>
        <div class="col-xs-12">
            <div class="col-xs-6">Password: </div>
            <div class="col-xs-6"><input type="password" value="" autocomplete="false" placeholder="Password" name="password" /></div>
        </div>
        <br/>
        <div class="col-xs-12" style="text-align: center">
            <input type="submit" value="Valider" />
        </div>
    </form>       
</div>
        <div class="clearfix"></div>