<div>
    <a href="user"><div style="border: solid 1px black; padding: 10px; margin: 10px; width: 250px; height: 250px; float: left;">Gestion des utilisateurs</div></a>
    <a href="member"><div style="border: solid 1px black; padding: 10px; margin: 10px; width: 250px; height: 250px; float: left;">Gestion des employ&eacute;s</div></a>
    <a href="catalogue"><div style="border: solid 1px black; padding: 10px; margin: 10px; width: 250px; height: 250px; float: left;">Gestion du catalogue</div></a>
    <a href="commande"><div style="border: solid 1px black; padding: 10px; margin: 10px; width: 250px; height: 250px; float: left;">Gestion des commandes</div></a>
    <!--a href=""><div style="border: solid 1px black; padding: 10px; margin: 10px; width: 250px; height: 250px; float: left;">Gestion des données de références</div></a -->
    <a href="stock"><div style="border: solid 1px black; padding: 10px; margin: 10px; width: 250px; height: 250px; float: left;">Gestion des stocks</div></a>
</div>
